feat: code changes for managed autoscaler
googleapis/nodejs-spanner pull request #1965
Opened 2023-12-08 03:16 UTC by alkatrivedi

This PR contains code changes for manages autoscaler.

2024-02-22 10:23 UTC, surbhigarg92 requested changes

2024-02-22 10:23 UTC, surbhigarg92 commented on samples/instance-with-autoscaling-config.js
> + * Copyright 2023 Google LLC
```suggestion
 * Copyright 2024 Google LLC
```

2024-02-22 10:23 UTC, surbhigarg92 commented on src/index.ts
> +          autoscalingConfig: config.autoscalingConfig,
We need to do changes for [Update Instance](https://github.com/googleapis/nodejs-spanner/blob/main/src/instance.ts#L1598) to handle below use case 
When autoscaling config is set then node and processing unit should not be passed

2024-03-06 09:12 UTC, alkatrivedi commented
Closing this PR, as there is no more need of this sample. I will add the similar samples using admin client.

2024-03-06 09:12 UTC, closed without merging